---
- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgresql_port }}"
    priv: "{{ item.priv | default(omit) }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_privileges }}"
  when: postgresql_users|length > 0 and repmgr_primary


- name: PostgreSQL | Update advanced privileges
  postgresql_privs:
    roles: "{{ item.roles }}"
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgresql_port }}"
    priv: "{{ item.priv | default(omit) }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
    type: "{{ item.type | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_advanced_privileges }}"
  when: postgresql_users|length > 0 and repmgr_primary
