---
- name: restart postgresql
  shell: 
    cmd: "{{ postgresql_service_restart_command }}"
    executable: /bin/bash

- name: reload postgresql
  shell: 
    cmd: "{{ postgresql_service_reload_command }}"
    executable: /bin/bash

- name: reload repmgr
  systemd:
    name: repmgrd
    state: restarted
  become: yes
